ruby '2.7.6'

gem "nokogiri"

source 'https://rubygems.org'
gem 'faraday', '~> 2.6'
gem 'coffee-rails', '~> 5.0'
gem 'activesupport'
gem 'activestorage', '~> 7.0', '>= 7.0.4'
gem 'activerecord', '~> 7.0', '>= 7.0.4'
gem 'activemodel', '~> 7.0', '>= 7.0.4'
gem 'activejob', '~> 7.0', '>= 7.0.4'
gem 'actionview', '~> 7.0', '>= 7.0.4'
gem 'actiontext', '~> 7.0', '>= 7.0.4'
gem 'actionpack', '~> 7.0', '>= 7.0.4'
gem 'actionmailer', '~> 7.0', '>= 7.0.4'
# gem 'actionmailbox', '~> 0.1.0'
# gem 'factory_bot'
gem 'stripe', '~> 7.1'
gem 'simplecov-html'
# gem 'simplecov', '~> 0.21.2'
gem 'shoulda-matchers', '~> 5.2'
# gem 'rack', '~> 3.0'
gem 'http-accept', '~> 2.2'
gem 'faraday-retry', '~> 2.0'
gem 'faraday-rack', '~> 2.0'
gem 'faraday-patron', '~> 1.0'
gem 'faraday-net_http_persistent', '~> 2.0', '>= 2.0.1'
gem 'faraday-net_http', '~> 3.0'
gem 'faraday-httpclient', '~> 2.0', '>= 2.0.1'
gem 'faraday-excon', '~> 2.1'
gem 'rails', '~> 7.0', '>= 7.0.4'
gem 'pg', '~> 1.4', '>= 1.4.3'
gem 'uglifier'
gem 'jquery-rails'
gem 'actioncable', '~> 7.0', '>= 7.0.4'
gem 'coffee-script'
gem 'devise'
gem 'devise_invitable'
# gem 'stripe'
gem 'mailgun-ruby'
gem 'nested_form_fields'
gem 'redcarpet'
gem 'deep_cloneable'
gem 'cancancan'
gem 'jquery-ui-rails'
gem 'validate_url'
gem 'hellosign-ruby-sdk'
gem 'closeio'
gem 'bootstrap-datepicker-rails'
gem 'jquery-timepicker-rails'
gem 'bootswatch-rails'
gem 'bootstrap-sass'
gem 'sass-rails'
gem 'jquery-datatables-rails'
gem 'textacular'
gem 'omniauth-github'
gem 'omniauth-rails_csrf_protection'
gem 'font-awesome-rails'
gem 'bootstrap-multiselect-rails'
gem 'kaminari'
gem 'paranoia'
gem 'resque'
gem 'active_model_serializers'
gem 'rest-client'
gem 'plaid'
gem 'openssl'
gem 'jwt'
gem 'octokit'
gem 'httparty'
gem 'sprockets-rails'
gem 'devise-two-factor'
gem 'rqrcode-rails3'

group :development do
  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem "letter_opener"
  gem 'bullet'
  gem 'rack-mini-profiler'
  gem 'listen'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'awesome_print'
  gem 'dotenv-rails'
  gem 'pry'
  gem 'hirb'
  gem 'factory_bot_rails', '~> 6.2'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
#  gem 'shoulda-matchers', '4.0.0.rc1'
  gem 'launchy'
  gem 'poltergeist'
  gem 'database_cleaner'
  gem 'webmock'
  gem 'vcr'
  gem 'simplecov', require: true
  gem 'coveralls', '~> 0.8', require: false
  gem 'stripe-ruby-mock'
  gem 'faker'
end

group :production do
  gem 'rails_12factor'
  gem 'puma'
  gem 'newrelic_rpm'
  gem 'bugsnag'
  gem 'lograge'
  gem 'oink'
end
